#!/bin/bash

PHP_VERSION=$(php -r "echo PHP_MAJOR_VERSION;")

echo $PHP_VERSION

if [ "$PHP_VERSION" -gt 5 ]; then
    CONFIG_FILE="phpunit-higher.xml"
else
    CONFIG_FILE="phpunit-lower.xml"
fi

vendor/bin/phpunit --configuration $CONFIG_FILE
